name: Docker Build & Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    uses: dev2b-tec/core-cicd-templates/.github/workflows/ci-docker.yml@main
    with:
      image-name: ghcr.io/${{ github.repository }}
      registry: ghcr.io
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
